version: '3.9'

services:
  app:
    image: yiisoftware/yii-php:8.1-fpm-nginx
    container_name: php8.1-VO
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_UPLOAD=50M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=50M